<table class="results" align="center">
<tr><td>January</td><td><a href="/calendar/jan/1">1</a> &middot; <a href="/calendar/jan/2">2</a> &middot; <a href="/calendar/jan/3">3</a> &middot; <a href="/calendar/jan/4">4</a> &middot; <a href="/calendar/jan/5">5</a> &middot; <a href="/calendar/jan/6">6</a> &middot; <a href="/calendar/jan/7">7</a> &middot; <a href="/calendar/jan/8">8</a> &middot; <a href="/calendar/jan/9">9</a> &middot; <a href="/calendar/jan/10">10</a> &middot; <a href="/calendar/jan/11">11</a> &middot; <a href="/calendar/jan/12">12</a> &middot; <a href="/calendar/jan/13">13</a> &middot; <a href="/calendar/jan/14">14</a> &middot; <a href="/calendar/jan/15">15</a> &middot; <a href="/calendar/jan/16">16</a> &middot; <a href="/calendar/jan/17">17</a> &middot; <a href="/calendar/jan/18">18</a> &middot; <a href="/calendar/jan/19">19</a> &middot; <a href="/calendar/jan/20">20</a> &middot; <a href="/calendar/jan/21">21</a> &middot; <a href="/calendar/jan/22">22</a> &middot; <a href="/calendar/jan/23">23</a> &middot; <a href="/calendar/jan/24">24</a> &middot; <a href="/calendar/jan/25">25</a> &middot; <a href="/calendar/jan/26">26</a> &middot; <a href="/calendar/jan/27">27</a> &middot; <a href="/calendar/jan/28">28</a> &middot; <a href="/calendar/jan/29">29</a> &middot; <a href="/calendar/jan/30">30</a> &middot; <a href="/calendar/jan/31">31</a></td></tr>
<tr><td>February</td><td><a href="/calendar/feb/1">1</a> &middot; <a href="/calendar/feb/2">2</a> &middot; <a href="/calendar/feb/3">3</a> &middot; <a href="/calendar/feb/4">4</a> &middot; <a href="/calendar/feb/5">5</a> &middot; <a href="/calendar/feb/6">6</a> &middot; <a href="/calendar/feb/7">7</a> &middot; <a href="/calendar/feb/8">8</a> &middot; <a href="/calendar/feb/9">9</a> &middot; <a href="/calendar/feb/10">10</a> &middot; <a href="/calendar/feb/11">11</a> &middot; <a href="/calendar/feb/12">12</a> &middot; <a href="/calendar/feb/13">13</a> &middot; <a href="/calendar/feb/14">14</a> &middot; <a href="/calendar/feb/15">15</a> &middot; <a href="/calendar/feb/16">16</a> &middot; <a href="/calendar/feb/17">17</a> &middot; <a href="/calendar/feb/18">18</a> &middot; <a href="/calendar/feb/19">19</a> &middot; <a href="/calendar/feb/20">20</a> &middot; <a href="/calendar/feb/21">21</a> &middot; <a href="/calendar/feb/22">22</a> &middot; <a href="/calendar/feb/23">23</a> &middot; <a href="/calendar/feb/24">24</a> &middot; <a href="/calendar/feb/25">25</a> &middot; <a href="/calendar/feb/26">26</a> &middot; <a href="/calendar/feb/27">27</a> &middot; <a href="/calendar/feb/28">28</a> &middot; <a href="/calendar/feb/29">29</a></td></tr>
<tr><td>March</td><td><a href="/calendar/mar/1">1</a> &middot; <a href="/calendar/mar/2">2</a> &middot; <a href="/calendar/mar/3">3</a> &middot; <a href="/calendar/mar/4">4</a> &middot; <a href="/calendar/mar/5">5</a> &middot; <a href="/calendar/mar/6">6</a> &middot; <a href="/calendar/mar/7">7</a> &middot; <a href="/calendar/mar/8">8</a> &middot; <a href="/calendar/mar/9">9</a> &middot; <a href="/calendar/mar/10">10</a> &middot; <a href="/calendar/mar/11">11</a> &middot; <a href="/calendar/mar/12">12</a> &middot; <a href="/calendar/mar/13">13</a> &middot; <a href="/calendar/mar/14">14</a> &middot; <a href="/calendar/mar/15">15</a> &middot; <a href="/calendar/mar/16">16</a> &middot; <a href="/calendar/mar/17">17</a> &middot; <a href="/calendar/mar/18">18</a> &middot; <a href="/calendar/mar/19">19</a> &middot; <a href="/calendar/mar/20">20</a> &middot; <a href="/calendar/mar/21">21</a> &middot; <a href="/calendar/mar/22">22</a> &middot; <a href="/calendar/mar/23">23</a> &middot; <a href="/calendar/mar/24">24</a> &middot; <a href="/calendar/mar/25">25</a> &middot; <a href="/calendar/mar/26">26</a> &middot; <a href="/calendar/mar/27">27</a> &middot; <a href="/calendar/mar/28">28</a> &middot; <a href="/calendar/mar/29">29</a> &middot; <a href="/calendar/mar/30">30</a> &middot; <a href="/calendar/mar/31">31</a></td></tr>
<tr><td>April</td><td><a href="/calendar/apr/1">1</a> &middot; <a href="/calendar/apr/2">2</a> &middot; <a href="/calendar/apr/3">3</a> &middot; <a href="/calendar/apr/4">4</a> &middot; <a href="/calendar/apr/5">5</a> &middot; <a href="/calendar/apr/6">6</a> &middot; <a href="/calendar/apr/7">7</a> &middot; <a href="/calendar/apr/8">8</a> &middot; <a href="/calendar/apr/9">9</a> &middot; <a href="/calendar/apr/10">10</a> &middot; <a href="/calendar/apr/11">11</a> &middot; <a href="/calendar/apr/12">12</a> &middot; <a href="/calendar/apr/13">13</a> &middot; <a href="/calendar/apr/14">14</a> &middot; <a href="/calendar/apr/15">15</a> &middot; <a href="/calendar/apr/16">16</a> &middot; <a href="/calendar/apr/17">17</a> &middot; <a href="/calendar/apr/18">18</a> &middot; <a href="/calendar/apr/19">19</a> &middot; <a href="/calendar/apr/20">20</a> &middot; <a href="/calendar/apr/21">21</a> &middot; <a href="/calendar/apr/22">22</a> &middot; <a href="/calendar/apr/23">23</a> &middot; <a href="/calendar/apr/24">24</a> &middot; <a href="/calendar/apr/25">25</a> &middot; <a href="/calendar/apr/26">26</a> &middot; <a href="/calendar/apr/27">27</a> &middot; <a href="/calendar/apr/28">28</a> &middot; <a href="/calendar/apr/29">29</a> &middot; <a href="/calendar/apr/30">30</a></td></tr>
<tr><td>May</td><td><a href="/calendar/may/1">1</a> &middot; <a href="/calendar/may/2">2</a> &middot; <a href="/calendar/may/3">3</a> &middot; <a href="/calendar/may/4">4</a> &middot; <a href="/calendar/may/5">5</a> &middot; <a href="/calendar/may/6">6</a> &middot; <a href="/calendar/may/7">7</a> &middot; <a href="/calendar/may/8">8</a> &middot; <a href="/calendar/may/9">9</a> &middot; <a href="/calendar/may/10">10</a> &middot; <a href="/calendar/may/11">11</a> &middot; <a href="/calendar/may/12">12</a> &middot; <a href="/calendar/may/13">13</a> &middot; <a href="/calendar/may/14">14</a> &middot; <a href="/calendar/may/15">15</a> &middot; <a href="/calendar/may/16">16</a> &middot; <a href="/calendar/may/17">17</a> &middot; <a href="/calendar/may/18">18</a> &middot; <a href="/calendar/may/19">19</a> &middot; <a href="/calendar/may/20">20</a> &middot; <a href="/calendar/may/21">21</a> &middot; <a href="/calendar/may/22">22</a> &middot; <a href="/calendar/may/23">23</a> &middot; <a href="/calendar/may/24">24</a> &middot; <a href="/calendar/may/25">25</a> &middot; <a href="/calendar/may/26">26</a> &middot; <a href="/calendar/may/27">27</a> &middot; <a href="/calendar/may/28">28</a> &middot; <a href="/calendar/may/29">29</a> &middot; <a href="/calendar/may/30">30</a> &middot; <a href="/calendar/may/31">31</a></td></tr>
<tr><td>June</td><td><a href="/calendar/jun/1">1</a> &middot; <a href="/calendar/jun/2">2</a> &middot; <a href="/calendar/jun/3">3</a> &middot; <a href="/calendar/jun/4">4</a> &middot; <a href="/calendar/jun/5">5</a> &middot; <a href="/calendar/jun/6">6</a> &middot; <a href="/calendar/jun/7">7</a> &middot; <a href="/calendar/jun/8">8</a> &middot; <a href="/calendar/jun/9">9</a> &middot; <a href="/calendar/jun/10">10</a> &middot; <a href="/calendar/jun/11">11</a> &middot; <a href="/calendar/jun/12">12</a> &middot; <a href="/calendar/jun/13">13</a> &middot; <a href="/calendar/jun/14">14</a> &middot; <a href="/calendar/jun/15">15</a> &middot; <a href="/calendar/jun/16">16</a> &middot; <a href="/calendar/jun/17">17</a> &middot; <a href="/calendar/jun/18">18</a> &middot; <a href="/calendar/jun/19">19</a> &middot; <a href="/calendar/jun/20">20</a> &middot; <a href="/calendar/jun/21">21</a> &middot; <a href="/calendar/jun/22">22</a> &middot; <a href="/calendar/jun/23">23</a> &middot; <a href="/calendar/jun/24">24</a> &middot; <a href="/calendar/jun/25">25</a> &middot; <a href="/calendar/jun/26">26</a> &middot; <a href="/calendar/jun/27">27</a> &middot; <a href="/calendar/jun/28">28</a> &middot; <a href="/calendar/jun/29">29</a> &middot; <a href="/calendar/jun/30">30</a></td></tr>
<tr><td>July</td><td><a href="/calendar/jul/1">1</a> &middot; <a href="/calendar/jul/2">2</a> &middot; <a href="/calendar/jul/3">3</a> &middot; <a href="/calendar/jul/4">4</a> &middot; <a href="/calendar/jul/5">5</a> &middot; <a href="/calendar/jul/6">6</a> &middot; <a href="/calendar/jul/7">7</a> &middot; <a href="/calendar/jul/8">8</a> &middot; <a href="/calendar/jul/9">9</a> &middot; <a href="/calendar/jul/10">10</a> &middot; <a href="/calendar/jul/11">11</a> &middot; <a href="/calendar/jul/12">12</a> &middot; <a href="/calendar/jul/13">13</a> &middot; <a href="/calendar/jul/14">14</a> &middot; <a href="/calendar/jul/15">15</a> &middot; <a href="/calendar/jul/16">16</a> &middot; <a href="/calendar/jul/17">17</a> &middot; <a href="/calendar/jul/18">18</a> &middot; <a href="/calendar/jul/19">19</a> &middot; <a href="/calendar/jul/20">20</a> &middot; <a href="/calendar/jul/21">21</a> &middot; <a href="/calendar/jul/22">22</a> &middot; <a href="/calendar/jul/23">23</a> &middot; <a href="/calendar/jul/24">24</a> &middot; <a href="/calendar/jul/25">25</a> &middot; <a href="/calendar/jul/26">26</a> &middot; <a href="/calendar/jul/27">27</a> &middot; <a href="/calendar/jul/28">28</a> &middot; <a href="/calendar/jul/29">29</a> &middot; <a href="/calendar/jul/30">30</a> &middot; <a href="/calendar/jul/31">31</a></td></tr>
<tr><td>August</td><td><a href="/calendar/aug/1">1</a> &middot; <a href="/calendar/aug/2">2</a> &middot; <a href="/calendar/aug/3">3</a> &middot; <a href="/calendar/aug/4">4</a> &middot; <a href="/calendar/aug/5">5</a> &middot; <a href="/calendar/aug/6">6</a> &middot; <a href="/calendar/aug/7">7</a> &middot; <a href="/calendar/aug/8">8</a> &middot; <a href="/calendar/aug/9">9</a> &middot; <a href="/calendar/aug/10">10</a> &middot; <a href="/calendar/aug/11">11</a> &middot; <a href="/calendar/aug/12">12</a> &middot; <a href="/calendar/aug/13">13</a> &middot; <a href="/calendar/aug/14">14</a> &middot; <a href="/calendar/aug/15">15</a> &middot; <a href="/calendar/aug/16">16</a> &middot; <a href="/calendar/aug/17">17</a> &middot; <a href="/calendar/aug/18">18</a> &middot; <a href="/calendar/aug/19">19</a> &middot; <a href="/calendar/aug/20">20</a> &middot; <a href="/calendar/aug/21">21</a> &middot; <a href="/calendar/aug/22">22</a> &middot; <a href="/calendar/aug/23">23</a> &middot; <a href="/calendar/aug/24">24</a> &middot; <a href="/calendar/aug/25">25</a> &middot; <a href="/calendar/aug/26">26</a> &middot; <a href="/calendar/aug/27">27</a> &middot; <a href="/calendar/aug/28">28</a> &middot; <a href="/calendar/aug/29">29</a> &middot; <a href="/calendar/aug/30">30</a> &middot; <a href="/calendar/aug/31">31</a></td></tr>
<tr><td>September</td><td><a href="/calendar/sep/1">1</a> &middot; <a href="/calendar/sep/2">2</a> &middot; <a href="/calendar/sep/3">3</a> &middot; <a href="/calendar/sep/4">4</a> &middot; <a href="/calendar/sep/5">5</a> &middot; <a href="/calendar/sep/6">6</a> &middot; <a href="/calendar/sep/7">7</a> &middot; <a href="/calendar/sep/8">8</a> &middot; <a href="/calendar/sep/9">9</a> &middot; <a href="/calendar/sep/10">10</a> &middot; <a href="/calendar/sep/11">11</a> &middot; <a href="/calendar/sep/12">12</a> &middot; <a href="/calendar/sep/13">13</a> &middot; <a href="/calendar/sep/14">14</a> &middot; <a href="/calendar/sep/15">15</a> &middot; <a href="/calendar/sep/16">16</a> &middot; <a href="/calendar/sep/17">17</a> &middot; <a href="/calendar/sep/18">18</a> &middot; <a href="/calendar/sep/19">19</a> &middot; <a href="/calendar/sep/20">20</a> &middot; <a href="/calendar/sep/21">21</a> &middot; <a href="/calendar/sep/22">22</a> &middot; <a href="/calendar/sep/23">23</a> &middot; <a href="/calendar/sep/24">24</a> &middot; <a href="/calendar/sep/25">25</a> &middot; <a href="/calendar/sep/26">26</a> &middot; <a href="/calendar/sep/27">27</a> &middot; <a href="/calendar/sep/28">28</a> &middot; <a href="/calendar/sep/29">29</a> &middot; <a href="/calendar/sep/30">30</a></td></tr>
<tr><td>October</td><td><a href="/calendar/oct/1">1</a> &middot; <a href="/calendar/oct/2">2</a> &middot; <a href="/calendar/oct/3">3</a> &middot; <a href="/calendar/oct/4">4</a> &middot; <a href="/calendar/oct/5">5</a> &middot; <a href="/calendar/oct/6">6</a> &middot; <a href="/calendar/oct/7">7</a> &middot; <a href="/calendar/oct/8">8</a> &middot; <a href="/calendar/oct/9">9</a> &middot; <a href="/calendar/oct/10">10</a> &middot; <a href="/calendar/oct/11">11</a> &middot; <a href="/calendar/oct/12">12</a> &middot; <a href="/calendar/oct/13">13</a> &middot; <a href="/calendar/oct/14">14</a> &middot; <a href="/calendar/oct/15">15</a> &middot; <a href="/calendar/oct/16">16</a> &middot; <a href="/calendar/oct/17">17</a> &middot; <a href="/calendar/oct/18">18</a> &middot; <a href="/calendar/oct/19">19</a> &middot; <a href="/calendar/oct/20">20</a> &middot; <a href="/calendar/oct/21">21</a> &middot; <a href="/calendar/oct/22">22</a> &middot; <a href="/calendar/oct/23">23</a> &middot; <a href="/calendar/oct/24">24</a> &middot; <a href="/calendar/oct/25">25</a> &middot; <a href="/calendar/oct/26">26</a> &middot; <a href="/calendar/oct/27">27</a> &middot; <a href="/calendar/oct/28">28</a> &middot; <a href="/calendar/oct/29">29</a> &middot; <a href="/calendar/oct/30">30</a> &middot; <a href="/calendar/oct/31">31</a></td></tr>
<tr><td>November</td><td><a href="/calendar/nov/1">1</a> &middot; <a href="/calendar/nov/2">2</a> &middot; <a href="/calendar/nov/3">3</a> &middot; <a href="/calendar/nov/4">4</a> &middot; <a href="/calendar/nov/5">5</a> &middot; <a href="/calendar/nov/6">6</a> &middot; <a href="/calendar/nov/7">7</a> &middot; <a href="/calendar/nov/8">8</a> &middot; <a href="/calendar/nov/9">9</a> &middot; <a href="/calendar/nov/10">10</a> &middot; <a href="/calendar/nov/11">11</a> &middot; <a href="/calendar/nov/12">12</a> &middot; <a href="/calendar/nov/13">13</a> &middot; <a href="/calendar/nov/14">14</a> &middot; <a href="/calendar/nov/15">15</a> &middot; <a href="/calendar/nov/16">16</a> &middot; <a href="/calendar/nov/17">17</a> &middot; <a href="/calendar/nov/18">18</a> &middot; <a href="/calendar/nov/19">19</a> &middot; <a href="/calendar/nov/20">20</a> &middot; <a href="/calendar/nov/21">21</a> &middot; <a href="/calendar/nov/22">22</a> &middot; <a href="/calendar/nov/23">23</a> &middot; <a href="/calendar/nov/24">24</a> &middot; <a href="/calendar/nov/25">25</a> &middot; <a href="/calendar/nov/26">26</a> &middot; <a href="/calendar/nov/27">27</a> &middot; <a href="/calendar/nov/28">28</a> &middot; <a href="/calendar/nov/29">29</a> &middot; <a href="/calendar/nov/30">30</a></td></tr>
<tr><td>December</td><td><a href="/calendar/dec/1">1</a> &middot; <a href="/calendar/dec/2">2</a> &middot; <a href="/calendar/dec/3">3</a> &middot; <a href="/calendar/dec/4">4</a> &middot; <a href="/calendar/dec/5">5</a> &middot; <a href="/calendar/dec/6">6</a> &middot; <a href="/calendar/dec/7">7</a> &middot; <a href="/calendar/dec/8">8</a> &middot; <a href="/calendar/dec/9">9</a> &middot; <a href="/calendar/dec/10">10</a> &middot; <a href="/calendar/dec/11">11</a> &middot; <a href="/calendar/dec/12">12</a> &middot; <a href="/calendar/dec/13">13</a> &middot; <a href="/calendar/dec/14">14</a> &middot; <a href="/calendar/dec/15">15</a> &middot; <a href="/calendar/dec/16">16</a> &middot; <a href="/calendar/dec/17">17</a> &middot; <a href="/calendar/dec/18">18</a> &middot; <a href="/calendar/dec/19">19</a> &middot; <a href="/calendar/dec/20">20</a> &middot; <a href="/calendar/dec/21">21</a> &middot; <a href="/calendar/dec/22">22</a> &middot; <a href="/calendar/dec/23">23</a> &middot; <a href="/calendar/dec/24">24</a> &middot; <a href="/calendar/dec/25">25</a> &middot; <a href="/calendar/dec/26">26</a> &middot; <a href="/calendar/dec/27">27</a> &middot; <a href="/calendar/dec/28">28</a> &middot; <a href="/calendar/dec/29">29</a> &middot; <a href="/calendar/dec/30">30</a> &middot; <a href="/calendar/dec/31">31</a></td></tr>
</table>
<?php
// script az egész újragenerálásához, de egyenként fölösleges ugyanaz megcsinálni
/*
echo '</table>';

$months = array(
	'January' => 31,
	'February' => 29,
	'March' => 31,
	'April' => 30,
	'May' => 31,
	'June' => 30,
	'July' => 31,
	'August' => 31,
	'September' => 30,
	'October' => 31,
	'November' => 30,
	'December' => 31
);
$mon_s = array(
	'January' => 'jan',
	'February' => 'feb',
	'March' => 'mar',
	'April' => 'apr',
	'May' => 'may',
	'June' => 'jun',
	'July' => 'jul',
	'August' => 'aug',
	'September' => 'sep',
	'October' => 'oct',
	'November' => 'nov',
	'December' => 'dec'
);

echo "<table>\n";
foreach ($months as $m => $days) {
	echo '<tr><td>'.$m.'</td>';
	echo '<td>';
	for ($i = 1; $i <= $days; $i++) {
		echo '<a href="/calendar/'.$mon_s[$m].'/'.$i.'">'.$i.'</a>';
		echo ' &middot; ';
	}
	echo "</td></tr>\n";
}
echo "</table>\n";*/
?>